---
- name: Configure interfaces for SD-WAN topology
  hosts:
    - iac-hub
    - iac-spk1
    - iac-spk2
  gather_facts: no
  collections:
    - fortinet.fortios

  tasks:

    - name: Configure interfaces on iac-hub
      when: inventory_hostname == "iac-hub"
      fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          name: "{{ item.name }}"
          ip: "{{ item.ip }}"
          allowaccess: ["ping", "http", "https", "fgfm"] 
          status: "up"
          mode: "static"
          description: "Configured via Ansible Playbook"
      loop:
        - { name: "port2", ip: "172.30.0.250/24" }
        - { name: "port3", ip: "6.2.0.10/24" }
        - { name: "port1", ip: "6.2.3.10/24" }

    - name: Configure interfaces on iac-spk1
      when: inventory_hostname == "iac-spk1"
      fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          name: "{{ item.name }}"
          ip: "{{ item.ip }}"
          allowaccess: ["ping", "http", "https", "fgfm"]  
          status: "up"
          mode: "static"
          description: "Configured via Ansible Playbook "
      loop:
        - { name: "port2", ip: "6.2.1.10/24" }
        - { name: "port3", ip: "192.168.233.33/24" }
        - { name: "port1", ip: "6.2.4.10/24" }

    - name: Configure interfaces on iac-spk2
      when: inventory_hostname == "iac-spk2"
      fortios_system_interface:
        vdom: "root"
        state: "present"
        system_interface:
          name: "{{ item.name }}"
          ip: "{{ item.ip }}"
          allowaccess: ["ping", "http", "https", "fgfm"]  
          status: "up"
          mode: "static"
          description: "Configured via Ansible Playbook"
      loop:
        - { name: "port1", ip: "6.2.5.10/24" }
        - { name: "port2", ip: "6.2.2.10/24" }
        - { name: "port3", ip: "192.168.233.44/24" }
