---
- name: Synchronize FortiGates with FortiManager
  hosts: iac-fmg
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortimanager

  vars:
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Install device configuration
      community.fortios.fmgr_device_config:
        adom: "root"
        device_unique_name: "iac-hub"
        install_config: "enable"
