---
- name: Configure static route using SD-WAN zone on Spoke1 (iac-spk1)
  hosts: iac-spk1
  connection: httpapi
  gather_facts: no
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Add default route via SD-WAN internet zone
      fortinet.fortios.fortios_router_static:
        vdom: "{{ vdom }}"
        access_token: "{{ fortios_access_token }}"
        state: "present"
        router_static:
          seq_num: 1
          dst: "172.30.0.250/24"
          distance: 1
          device: "internet"  # Using the SD-WAN zone as next hop
          comment: "iac-spk1-route via SD-WAN internet zone"
